/**
 * Achievement map info
 * 勋章图片资源信息
 */
export default class AchievementMapInfo {
  off_3: Resource = $r('app.media.ic_badge_3_off');
  on_3: Resource = $r('app.media.ic_badge_3_on');
  off_7: Resource = $r('app.media.ic_badge_7_off');
  on_7: Resource = $r('app.media.ic_badge_7_on');
  off_30: Resource = $r('app.media.ic_badge_30_off');
  on_30: Resource = $r('app.media.ic_badge_30_on');
  off_50: Resource = $r('app.media.ic_badge_50_off');
  on_50: Resource = $r('app.media.ic_badge_50_on');
  off_73: Resource = $r('app.media.ic_badge_73_off');
  on_73: Resource = $r('app.media.ic_badge_73_on');
  off_99: Resource = $r('app.media.ic_badge_99_off');
  on_99: Resource = $r('app.media.ic_badge_99_on');
}
